swagger: "2.0"
info:
  description: "This is the format in which the parsed insurance card data will be returned"
  version: "1.0.0"
  title: "Insurance service"
host: "7auqotnz25.execute-api.us-east-2.amazonaws.com"
basePath: "/prod/"
tags:
- name: "insurance"
  description: "Data from the insurance card"
schemes:
- "https"
- "http"
paths:
  /image:
    post:
      summary: "upload the insurance card"
      description: ""
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created insurance object"
        required: true
        schema:
          $ref: "#/definitions/Image"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: '#/definitions/Insurance'
definitions:
  Image:
    type: "object"
    properties:
      type:
        type: "string"
        example: "ins"
      name:
        type: "string"
        description: "name of the image, can be anything"
      image:
        type: "string"
        description: "a base64 encoded string value for the image, must be < 100K"
  Insurance:
    type: "object"
    properties:
      policyNumber:
        type: "string"
      effectiveDate:
        type: "string"
      expDate:
        type: "string"
      insurer:
        type: "string"
      vehicleYear:
        type: "number"
      vehicleMake:
        type: "string"
      vehicleModel:
        type: "string"
      vin:
        type: "number"